version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    user: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root #设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - /Users/mac/voldocker/mysql/data:/var/lib/mysql/:rw #数据文件挂载
      - /Users/mac/voldocker/mysql/conf:/etc/mysql/conf.d #配置文件挂载 /etc/mysql/conf.d
      - /Users/mac/voldocker/mysql/log:/var/log/mysql #日志文件挂载
  redis:
    image: redis:7
    user: redis
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - /Users/mac/voldocker/redis/data:/data/:rw #数据文件挂载
    ports:
      - 6379:6379
  nginx:
    image: nginx:1.22
    container_name: nginx
    volumes:
      - /Users/mac/voldocker/nginx/nginx.conf:/etc/nginx/nginx.conf #配置文件挂载
      - /Users/mac/voldocker/nginx/html:/usr/share/nginx/html #静态资源根目录挂载
      - /Users/mac/voldocker/nginx/log:/var/log/nginx #日志文件挂载
    ports:
      - 80:80
  rabbitmq:
    # image: rabbitmq:3.10.18-management
    # image: rabbitmq:3.6.0-management
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    # user: rabbitmq
    # volumes:
      # - /Users/mac/voldocker/rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
      # - /Users/mac/voldocker/rabbitmq/log:/var/log/rabbitmq #日志文件挂载
    ports:
      - 5672:5672
      - 15672:15672
  elasticsearch:
    image: elasticsearch:7.17.7
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms2048m -Xmx3036m" #设置使用jvm内存大小
    volumes:
      - /Users/mac/voldocker/elasticsearch/plugins:/usr/share/elasticsearch/plugins:rw #插件文件挂载
      - /Users/mac/voldocker/elasticsearch/data:/usr/share/elasticsearch/data:rw #数据文件挂载
    ports:
      - 9200:9200
      - 9300:9300
  logstash:
    image: logstash:7.17.3
    container_name: logstash
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /Users/mac/voldocker/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
  kibana:
    image: kibana:7.17.3
    container_name: kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601
  mongo:
    image: mongo:4
    container_name: mongo
    volumes:
      # - /Users/mac/voldocker/mongo/db:/data/db:rw #数据文件挂载
      - /Users/mac/voldocker/mongo/db:/data:rw #数据文件挂载
    ports:
      - 27017:27017

