spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 5 # Initial size of the connection pool
      min-idle: 10 # Minimum number of idle connections in the pool
      max-active: 20 # Maximum number of active connections in the pool
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*' # Requests that should be excluded from statistics
      stat-view-servlet: # Login username and password for the monitoring web page
        login-username: druid
        login-password: druid
  redis:
    host: localhost # Redis server address
    database: 0 # Redis database index (default is 0)
    port: 6379 # Redis server connection port
    password: # Redis server connection password (default is empty)
    timeout: 300ms # Connection timeout (in milliseconds)

minio:
  endpoint: http://localhost:9000 # MinIO service address
  bucketName: mall # Bucket name for object storage
  accessKey: minioadmin # Access key for MinIO
  secretKey: minioadmin # Secret key for MinIO access

logging:
  level:
    root: info
    com.elliot.mall: debug

logstash:
  host: localhost
  enableInnerLog: false
