spring:
  datasource:
    url: jdbc:mysql://db:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false # Database URL
    username: reader # Database username
    password: 123456 # Database password
    druid:
      initial-size: 5 # Initial size of the connection pool
      min-idle: 10 # Minimum number of idle connections in the pool
      max-active: 20 # Maximum number of active connections in the pool
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" # URLs to exclude from statistics collection
      stat-view-servlet: # Login username and password for accessing the monitoring page
        login-username: druid
        login-password: druid
  redis:
    host: redis # Redis server address
    database: 0 # Redis database index (default is 0)
    port: 6379 # Redis server connection port
    password: # Redis server connection password (default is empty)
    timeout: 300ms # Connection timeout in milliseconds

minio:
  endpoint: http://192.168.0.101:9090 # MinIO server address
  bucketName: mall # Bucket name
  accessKey: minioadmin # Access key for accessing MinIO
  secretKey: minioadmin # Secret key for accessing MinIO

logging:
  file:
    path: /var/logs # Path to store log files
  level:
    root: info # Root logging level
    com.elliot.mall: info # Logging level for the specified package and its sub-packages

logstash:
  host: logstash # Logstash server address
